# -*- coding: utf-8 -*-
{
    'name': "Chariots CORE Module",
    'summary': """
        ERP de Chariots adaptado con A3 y KFC.
    """,
    'description': """
        Este módulo tiene como objetivo...
    """,
    "category": "Generic Modules",
    "website": "https://melkart.io",
    "author": "Melkart O&B",
    "license": "LGPL-3",
    'depends': [
        'base',
        'account',
        'account_accountant',
        'account_sepa',
        'l10n_es_aeat_sii',
        'l10n_es_toponyms',
        'l10n_es_partner',
        'l10n_es_partner_mercantil',
        'documents',
        'hr_expense_invoice',
        'chariots_next_prev_button',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/settings.xml',
        'data/analytic_accounts.xml',
        'data/cron.xml',
        'data/attach.xml',
        'data/hr_expense_codes.xml',
        'data/mail_data.xml',
        'data/journals_kfc.xml',
        'data/delete_invoices.xml',
        'views/menuitem.xml',
        'views/hr_employee.xml',
        'views/hr_expense.xml',
        'views/account_invoice.xml',
        'views/account_tax.xml',
        'views/account_move.xml',
        'views/account_analytic.xml',
        'views/account_journal.xml',
        'views/assets.xml',
        'views/account_invoice_excel.xml',
        'views/res_partner_supplier.xml',
        'views/account_bank_statement_views.xml',
        'views/account_batch_payment.xml',
        'views/account_payment.xml',
        'views/import_purpose/a3_odoo.xml',
        'views/import_purpose/a3_move.xml',
        'views/import_purpose/a3_product.xml',
        'views/import_purpose/a3_partner.xml',
        'views/import_purpose/kfc_category.xml',
        'views/import_purpose/kfc_product.xml',
        'views/import_purpose/kfc_store.xml',
        'views/import_purpose/kfc_tax.xml',
        'views/import_purpose/kfc_time_range.xml',
        'views/import_purpose/kfc_pay_method.xml',
        'views/import_purpose/kfc_channel.xml',
        'views/import_purpose/kfc_sale.xml',
        'views/extra/custom_report.xml',
        'views/wizard_migrate_multi_company.xml',
        'views/wizard_fix_errors.xml',
        'report/account_invoice_report_view.xml',
        'report/kfc_sale_report_view.xml',


    ],
    'demo': [],
    "qweb":[],
    'application': True,
    "installable": True,
}
