from . import chariots_a3_move
from . import chariots_a3_product
from . import chariots_a3_odoo
from . import chariots_a3_partner
from . import kfc_category
from . import kfc_channel
from . import kfc_pay_method
from . import kfc_product
from . import kfc_sale
from . import kfc_store
from . import kfc_tax
from . import kfc_time_range
